/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Adrián
 */
public class Elegir extends javax.swing.JDialog {

    /**
     * Creates new form Elegir
     */
    PrincipalGestion g;
    JFrame padre;
    NModificar nm;

    public Elegir(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        padre = (JFrame) parent;
        initComponents();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((pantalla.width / 2) - (this.getWidth() / 2), (pantalla.height / 2) - (this.getHeight() / 2));
        rellenoBotones();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btn1.setText("jButton1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("jButton2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String accion = g.getAccion();
        String tipo = g.getTipo();
        try {
            if (tipo.equals("Pieza")) {
                g.setTipo("tipo");
                nm = new NModificar(padre, accion, true);
                nm.setVisible(true);
                this.dispose();

            }
            if (tipo.equals("Marca")) {
                g.setTipo("modelo");
                nm = new NModificar(padre, accion, true);
                nm.setVisible(true);
                this.dispose();

            }
        } catch (SQLException ex) {
            Logger.getLogger(Elegir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String accion = g.getAccion();
        String tipo = g.getTipo();
        try {
            if (tipo.equals("Pieza")) {
                g.setTipo("pieza");
                nm = new NModificar(padre, accion, true);
                nm.setVisible(true);
                this.dispose();

            }
            if (tipo.equals("Marca")) {
                g.setTipo("marca");
                nm = new NModificar(padre, accion, true);
                nm.setVisible(true);
                this.dispose();

            }
        } catch (SQLException ex) {
            Logger.getLogger(Elegir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    public void rellenoBotones() throws SQLException {
        String tipo = g.getTipo();
        if (tipo == "Pieza") {
            btn1.setText(g.getAccion() + " tipo");
            btn2.setText(g.getAccion() + " pieza");
        }
        if (tipo == "Marca") {
            btn1.setText(g.getAccion() + " modelo");
            btn2.setText(g.getAccion() + " marca");
        }
        if (tipo == "Recambio") {
            /*g.setTipo("modelo");
            nm = new NModificar(padre, "Modifcar", true);
            nm.setVisible(true);*/
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    // End of variables declaration//GEN-END:variables
}
