/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import Registro.Registro;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpSetException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Adrián
 */
public class OpcionesEmpresa extends javax.swing.JDialog {

    /**
     * Creates new form OpcionesEmpresa
     */
    public static String elegido;
    PrincipalGestion intro = null;
    JFrame padre;

    public OpcionesEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (JFrame) parent;
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((pantalla.width / 2) - (this.getWidth() / 2), (pantalla.height / 2) - (this.getHeight() / 2));

        ImageIcon icon = new ImageIcon("iconos/logout.png");
        ImageIcon iconDef = new ImageIcon(icon.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));

        btnLogout.setIcon(iconDef);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        btnVMarca = new javax.swing.JButton();
        btnVPieza = new javax.swing.JButton();
        btnRecambio = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnLogout = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnVMarca.setText("Gestionar coches");
        btnVMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVMarcaActionPerformed(evt);
            }
        });

        btnVPieza.setText("Gestionar piezas");
        btnVPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVPiezaActionPerformed(evt);
            }
        });

        btnRecambio.setText("Gestionar recambios");
        btnRecambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecambioActionPerformed(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVPieza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecambio, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVPieza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVMarcaActionPerformed
        // TODO add your handling code here:
        setValor("Marca");
        try {
            intro = new PrincipalGestion();
        } catch (SQLException ex) {
            Logger.getLogger(OpcionesEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(OpcionesEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HelpSetException ex) {
            Logger.getLogger(OpcionesEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        padre.dispose();
        intro.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnVMarcaActionPerformed

    private void btnVPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVPiezaActionPerformed
        // TODO add your handling code here:
        setValor("Pieza");
        try {
            intro = new PrincipalGestion();
        } catch (SQLException ex) {
            Logger.getLogger(OpcionesEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(OpcionesEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HelpSetException ex) {
            Logger.getLogger(OpcionesEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        padre.setVisible(false);
        intro.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnVPiezaActionPerformed

    private void btnRecambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecambioActionPerformed
        // TODO add your handling code here:
        setValor("Recambio");
        try {
            intro = new PrincipalGestion();
        } catch (SQLException ex) {
            Logger.getLogger(OpcionesEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(OpcionesEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HelpSetException ex) {
            Logger.getLogger(OpcionesEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        padre.setVisible(false);
        intro.setVisible(true);
    }//GEN-LAST:event_btnRecambioActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Registro r = new Registro();
        r.setVisible(true);

    }//GEN-LAST:event_btnLogoutActionPerformed

    public String getValor() {
        return elegido;
    }

    public static void setValor(String el) {
        OpcionesEmpresa.elegido = el;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRecambio;
    private javax.swing.JButton btnVMarca;
    private javax.swing.JButton btnVPieza;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
